### PR TITLE
feat: Add mem_calloc()

### PR DESCRIPTION
**Pull request by AyushChakraborty**

### CODE REVIEW

**Comment by NavneetNayak** [comment]
@AyushChakraborty continue working on this please, calloc is good, also add string.h to the header file

**Comment by AyushChakraborty** [comment]
@NavneetNayak will do

**Comment by AyushChakraborty** [comment]
@NavneetNayak pls chk the mem_realloc() code

**Comment by NavneetNayak** [comment]
!bounty 200

**Comment by AyushChakraborty** [comment]
@NavneetNayak crazy bro 😤

**Comment by NavneetNayak** [comment]
!bounty 150

**Comment by AyushChakraborty** [comment]
@NavneetNayak can you explain why the drop in points?

**Comment by NavneetNayak** [comment]
@AyushChakraborty ya bro were doing point review and basically deciding if the points people have got are worth the code they wrote and it was kinda decided that for the difficulty 400 points was too much. 
This process is still ongoing ur points may increase or decrease based on how hard the issue is relative to other people who got points and how hard their issues were

**Comment by AyushChakraborty** [comment]
@NavneetNayak kk got it

**Pull request closed without merging**
